import { validateAdapterAst, executeInSandbox, type DetailedDiff } from '@orchestrator/core';
import { prisma } from '../db.js';
import { registerAndDeployPatch } from './canary.js';

export interface PatchGenerationTask {
  driftEventId: string;
  contractId: string;
  serviceName: string;
  endpointPath: string;
  expectedSchema: string[];
  diffDetails: DetailedDiff;
  samplePayload: unknown;
}

/**
 * Invokes Ollama local LLM or fallback algorithm to generate a pure ES6 data adapter
 */
export async function triggerPatchGeneration(task: PatchGenerationTask): Promise<void> {
  console.log(`[CognitiveReasoningEngine] Processing drift event ${task.driftEventId}...`);

  const ollamaBaseUrl = process.env.OLLAMA_BASE_URL || 'http://localhost:11434';
  const model = process.env.OLLAMA_MODEL || 'llama3';

  // Construct prompt strictly requiring single arrow function
  const prompt = `
You are an expert TypeScript/JavaScript systems engineer.
An upstream microservice has experienced API contract drift.
Generate a pure JavaScript data adapter function that transforms the NEW/OBSERVED payload back to the EXPECTED schema.

Service: ${task.serviceName}
Endpoint: ${task.endpointPath}
Expected Schema Fields: ${JSON.stringify(task.expectedSchema)}
Schema Differences:
- Missing Expected Fields: ${JSON.stringify(task.diffDetails.missingFields)}
- Added Upstream Fields: ${JSON.stringify(task.diffDetails.addedFields)}
- Type Mismatches: ${JSON.stringify(task.diffDetails.typeMismatches)}

Sample Observed Payload:
${JSON.stringify(task.samplePayload, null, 2)}

Strict Rules:
1. Output ONLY a valid ES6 arrow function, e.g.: (data) => ({ ...data, firstName: data.first_name })
2. Do NOT include markdown formatting, backticks, or explanatory text.
3. No imports, no network requests, no eval, no mutations. Pure transformation.
4. Use optional chaining and nullish coalescing (??).
`;

  let adapterCode = '';
  let reasoningTrace = '';

  try {
    const res = await fetch(`${ollamaBaseUrl}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model,
        prompt,
        stream: false,
        options: { temperature: 0.1 },
      }),
    });

    if (res.ok) {
      const data = (await res.json()) as { response: string };
      const rawText = data.response.trim();
      // Clean possible markdown code fence
      adapterCode = rawText.replace(/```(javascript|js)?/g, '').replace(/```/g, '').trim();
      reasoningTrace = `Generated by Ollama (${model}) with temperature 0.1`;
    } else {
      throw new Error(`Ollama returned status ${res.status}`);
    }
  } catch (err: unknown) {
    console.warn(`[CognitiveReasoningEngine] Ollama unavailable (${(err as Error).message}), using deterministic fallback generator.`);
    
    // Deterministic fallback adapter generation for zero-downtime resilience
    const mappings: string[] = [];
    for (const missing of task.diffDetails.missingFields) {
      const matched = task.diffDetails.addedFields.find(
        (a) => a.replace(/_/g, '').toLowerCase() === missing.toLowerCase()
      );
      if (matched) {
        mappings.push(`${missing}: data.${matched}`);
      }
    }

    adapterCode = `(data) => ({ ...data, ${mappings.join(', ')} })`;
    reasoningTrace = 'Synthesized via Deterministic AST Field-Mapping Fallback Engine';
  }

  // 1. AST Syntax & Security Verification
  const astCheck = validateAdapterAst(adapterCode);
  if (!astCheck.valid) {
    console.error(`[CognitiveReasoningEngine] AST Security Validation Failed:`, astCheck.errors);
    return;
  }

  // 2. Isolated VM Sandbox Dry-run Verification
  const sandboxCheck = executeInSandbox(adapterCode, task.samplePayload);
  if (!sandboxCheck.success) {
    console.error(`[CognitiveReasoningEngine] Sandbox Execution Error:`, sandboxCheck.error);
    return;
  }

  console.log(`[CognitiveReasoningEngine] Adapter verified successfully in sandbox (${sandboxCheck.executionTimeMs.toFixed(2)}ms)!`);

  // 3. Persist Patch in PostgreSQL
  const patch = await prisma.patchRegistry.create({
    data: {
      contractId: task.contractId,
      driftEventId: task.driftEventId,
      adapterCode,
      adapterSignature: `adapter_${task.serviceName}_v1`,
      confidenceScore: 0.95,
      status: 'CANARY',
      canaryPercent: 10,
    },
  });

  // 4. Log Governance Audit record
  await prisma.governanceAudit.create({
    data: {
      driftEventId: task.driftEventId,
      patchId: patch.id,
      status: 'AUTO_APPROVED',
      reasoningTrace,
      reviewer: 'CognitiveReasoningEngine',
      reviewNotes: 'AST verified and sandboxed pure transformation.',
    },
  });

  // 5. Deploy to Canary router
  await registerAndDeployPatch(patch.id, task.serviceName, adapterCode);
}
