// Live checks that need real external systems: migrations against Postgres, and Gemini.
// The full request pipeline is covered over HTTP in nest.test.mjs.
import test from 'node:test';
import assert from 'node:assert/strict';
import { resolve } from 'node:path';
import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';
import { generateText } from '@orchestrator/gemini-client';
import { InferenceService } from '../api-gateway/dist/cognitive/inference.service.js';

const migrationsFolder = resolve(
  import.meta.dirname,
  '../../packages/database/migrations',
);

test('migrations apply cleanly and are idempotent', async () => {
  assert.ok(
    process.env.TEST_DATABASE_URL,
    'TEST_DATABASE_URL must point to a disposable database',
  );
  const client = postgres(process.env.TEST_DATABASE_URL, {
    max: 1,
    onnotice: () => {},
  });
  try {
    await migrate(drizzle(client), { migrationsFolder });
    await migrate(drizzle(client), { migrationsFolder });
    const tables =
      await client`select table_name from information_schema.tables where table_schema = 'public'`;
    for (const table of [
      'organizations',
      'org_members',
      'consumers',
      'consumer_keys',
      'api_contracts',
    ])
      assert.ok(
        tables.some((row) => row.table_name === table),
        table,
      );
  } finally {
    await client.end();
  }
});

// Gemini tests call the real API, so they run only when a key is provided.
const geminiKey = process.env.TEST_GEMINI_API_KEY;
const geminiModel = process.env.TEST_GEMINI_MODEL || 'gemini-3.5-flash-lite';
const skipGemini = geminiKey ? false : 'TEST_GEMINI_API_KEY not set';

test(
  'live Gemini model produces a nonempty response',
  { skip: skipGemini },
  async () => {
    const response = await generateText({
      apiKey: geminiKey,
      model: geminiModel,
      prompt: 'Reply with the word OK.',
      timeoutMs: 60_000,
    });
    assert.ok(response.trim().length > 0);
  },
);

test(
  'Gemini generates a working adapter through InferenceService',
  { skip: skipGemini },
  async () => {
    const settings = {
      effective: async () => ({
        driftThreshold: 0.15,
        canaryPercent: 10,
        gemini: { apiKey: geminiKey, model: geminiModel },
      }),
    };
    const result = await new InferenceService(settings).generate({
      driftEventId: 'integration',
      contractId: 'integration',
      orgId: 'org',
      consumerId: 'consumer',
      consumerName: 'web',
      serviceName: 'integration',
      httpMethod: 'GET',
      endpointPath: '/users',
      expectedSchema: ['firstName:string'],
      diffDetails: {
        missingFields: ['firstName'],
        addedFields: ['first_name'],
        typeMismatches: [],
      },
      samplePayload: { first_name: 'Ada' },
    });
    assert.match(result.reasoningTrace, /^Generated by Gemini/);
    const { validateAdapterAst, executeInSandbox } =
      await import('@orchestrator/adapter-runtime');
    assert.equal(validateAdapterAst(result.adapterCode).valid, true);
    const executed = executeInSandbox(result.adapterCode, {
      first_name: 'Ada',
    });
    assert.equal(executed.success, true);
    assert.equal(executed.transformedOutput.firstName, 'Ada');
  },
);
