import { Injectable, Logger } from '@nestjs/common';
import { validateAdapterAst, executeInSandbox, type DetailedDiff } from '@orchestrator/core';
import { type DrizzleDb, patchRegistries, governanceAudits } from '@orchestrator/database';

export interface PatchGenerationTask {
  driftEventId: string;
  contractId: string;
  serviceName: string;
  endpointPath: string;
  expectedSchema: string[];
  diffDetails: DetailedDiff;
  samplePayload: unknown;
}

@Injectable()
export class CognitiveService {
  private readonly logger = new Logger(CognitiveService.name);

  async generateAndValidatePatch(db: DrizzleDb, task: PatchGenerationTask): Promise<string | null> {
    this.logger.log(`Processing cognitive patch generation for drift event: ${task.driftEventId}`);

    const ollamaBaseUrl = process.env.OLLAMA_BASE_URL || 'http://localhost:11434';
    const model = process.env.OLLAMA_MODEL || 'llama3';

    const prompt = `
You are an expert TypeScript/JavaScript systems engineer.
An upstream microservice has experienced API contract drift.
Generate a pure JavaScript data adapter function that transforms the NEW/OBSERVED payload back to the EXPECTED schema.

Service: ${task.serviceName}
Endpoint: ${task.endpointPath}
Expected Schema Fields: ${JSON.stringify(task.expectedSchema)}
Schema Differences:
- Missing Expected Fields: ${JSON.stringify(task.diffDetails.missingFields)}
- Added Upstream Fields: ${JSON.stringify(task.diffDetails.addedFields)}
- Type Mismatches: ${JSON.stringify(task.diffDetails.typeMismatches)}

Sample Observed Payload:
${JSON.stringify(task.samplePayload, null, 2)}

Strict Rules:
1. Output ONLY a valid ES6 arrow function, e.g.: (data) => ({ ...data, firstName: data.first_name })
2. Do NOT include markdown formatting, backticks, or explanatory text.
3. No imports, no network requests, no eval, no mutations. Pure transformation.
4. Use optional chaining and nullish coalescing (??).
`;

    let adapterCode = '';
    let reasoningTrace = '';

    try {
      const res = await fetch(`${ollamaBaseUrl}/api/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model,
          prompt,
          stream: false,
          options: { temperature: 0.1 },
        }),
      });

      if (res.ok) {
        const data = (await res.json()) as { response: string };
        adapterCode = data.response.replace(/```(javascript|js)?/g, '').replace(/```/g, '').trim();
        reasoningTrace = `Generated by Ollama (${model}) with ReAct prompt`;
      } else {
        throw new Error(`Ollama returned status ${res.status}`);
      }
    } catch (err: unknown) {
      this.logger.warn(`Ollama inference unavailable (${(err as Error).message}), invoking deterministic fallback adapter synthesizer.`);
      
      const mappings: string[] = [];
      for (const missing of task.diffDetails.missingFields) {
        const matched = task.diffDetails.addedFields.find(
          (a) => a.replace(/_/g, '').toLowerCase() === missing.toLowerCase()
        );
        if (matched) {
          mappings.push(`${missing}: data.${matched}`);
        }
      }

      adapterCode = `(data) => ({ ...data, ${mappings.join(', ')} })`;
      reasoningTrace = 'Synthesized via Deterministic AST Field-Mapping Fallback Engine';
    }

    // AST Safety validation
    const astCheck = validateAdapterAst(adapterCode);
    if (!astCheck.valid) {
      this.logger.error(`AST Validation failed: ${astCheck.errors.join(', ')}`);
      return null;
    }

    // VM Sandbox verification
    const sandboxCheck = executeInSandbox(adapterCode, task.samplePayload);
    if (!sandboxCheck.success) {
      this.logger.error(`Sandbox execution failed: ${sandboxCheck.error}`);
      return null;
    }

    this.logger.log(`Adapter verified in sandbox (${sandboxCheck.executionTimeMs.toFixed(2)}ms)!`);

    // Insert into Supabase via Drizzle ORM
    const [patch] = await db
      .insert(patchRegistries)
      .values({
        contractId: task.contractId,
        driftEventId: task.driftEventId,
        adapterCode,
        adapterSignature: `adapter_${task.serviceName}_v1`,
        confidenceScore: 0.95,
        status: 'CANARY',
        canaryPercent: 10,
      })
      .returning();

    await db.insert(governanceAudits).values({
      driftEventId: task.driftEventId,
      patchId: patch.id,
      status: 'AUTO_APPROVED',
      reasoningTrace,
      reviewer: 'CognitiveReasoningEngine',
      reviewNotes: 'AST verified and sandboxed pure transformation.',
    });

    return adapterCode;
  }
}
