import { Inject, Injectable, Logger } from '@nestjs/common';
import { generateText } from '@orchestrator/gemini-client';
import { OrgSettingsService } from '../orgs/org-settings.service.js';
import { buildRenameAdapter } from './fallback-adapter.js';
import type {
  GeneratedAdapter,
  PatchGenerationTask,
} from './patch-generation.js';

const FALLBACK_TRACE =
  'Synthesized via Deterministic AST Field-Mapping Fallback Engine';

// Mirrors what validateAdapterAst and the sandbox accept, so valid output is the norm.
const SYSTEM_INSTRUCTION = `You are an expert JavaScript systems engineer repairing API contract drift.
Return ONLY one synchronous JavaScript arrow function (data) => ... that converts the observed payload back to the expected schema.
Rules:
- No markdown, backticks, comments or explanation.
- Pure transformation: no imports, network, timers, eval, Function, this, globalThis, process, constructor, prototype or __proto__.
- Do not mutate the input; build and return a new object.
- Use optional chaining and nullish coalescing (??) for fields that may be absent.`;

@Injectable()
export class InferenceService {
  private readonly logger = new Logger(InferenceService.name);

  constructor(
    @Inject(OrgSettingsService) private readonly settings: OrgSettingsService,
  ) {}

  async generate(task: PatchGenerationTask): Promise<GeneratedAdapter> {
    // Each organization may bring its own Gemini key and model.
    const { apiKey, model } = (await this.settings.effective(task.orgId))
      .gemini;
    if (!apiKey) return this.fallback(task, 'GEMINI_API_KEY is not set');
    try {
      const response = await generateText({
        apiKey,
        model,
        systemInstruction: SYSTEM_INSTRUCTION,
        prompt: buildAdapterPrompt(task),
      });
      return {
        adapterCode: response.replace(/```(javascript|js)?/g, '').trim(),
        reasoningTrace: `Generated by Gemini (${model})`,
      };
    } catch (error: unknown) {
      return this.fallback(task, `Gemini unavailable: ${String(error)}`);
    }
  }

  private fallback(
    task: PatchGenerationTask,
    reason: string,
  ): GeneratedAdapter {
    this.logger.warn(`${reason}. Using field-rename fallback.`);
    return {
      adapterCode: buildRenameAdapter(task.diffDetails),
      reasoningTrace: FALLBACK_TRACE,
    };
  }
}

function buildAdapterPrompt(task: PatchGenerationTask): string {
  return `Service: ${task.serviceName}
Endpoint: ${task.httpMethod} ${task.endpointPath}
Expected schema (path:type tokens): ${JSON.stringify(task.expectedSchema)}
Missing expected fields: ${JSON.stringify(task.diffDetails.missingFields)}
Added upstream fields: ${JSON.stringify(task.diffDetails.addedFields)}
Type mismatches: ${JSON.stringify(task.diffDetails.typeMismatches)}

Sample observed payload:
${JSON.stringify(task.samplePayload, null, 2)}`;
}
