import { generateText } from '@orchestrator/ollama-client';
import { Injectable, Logger } from '@nestjs/common';
import type {
  PatchGenerationTask,
  GeneratedAdapter,
} from './patch-generation.js';

@Injectable()
export class InferenceService {
  private readonly logger = new Logger(InferenceService.name);

  async generate(task: PatchGenerationTask): Promise<GeneratedAdapter> {
    const ollamaBaseUrl =
      process.env.OLLAMA_BASE_URL || 'http://localhost:11434';
    const model = process.env.OLLAMA_MODEL || 'llama3';

    try {
      const response = await generateText({
        baseUrl: ollamaBaseUrl,
        model,
        prompt: buildAdapterPrompt(task),
      });
      return {
        adapterCode: response.replace(/```(javascript|js)?/g, '').trim(),
        reasoningTrace: `Generated by Ollama (${model})`,
      };
    } catch (error: unknown) {
      this.logger.warn(
        `Ollama unavailable: ${String(error)}. Using field-rename fallback.`,
      );
      return {
        adapterCode: buildRenameAdapter(task.diffDetails),
        reasoningTrace:
          'Synthesized via Deterministic AST Field-Mapping Fallback Engine',
      };
    }
  }
}

function buildAdapterPrompt(task: PatchGenerationTask): string {
  return `
You are an expert TypeScript/JavaScript systems engineer.
An upstream microservice has experienced API contract drift.
Generate a pure JavaScript data adapter function that transforms the NEW/OBSERVED payload back to the EXPECTED schema.

Service: ${task.serviceName}
Endpoint: ${task.endpointPath}
Expected Schema Fields: ${JSON.stringify(task.expectedSchema)}
Schema Differences:
- Missing Expected Fields: ${JSON.stringify(task.diffDetails.missingFields)}
- Added Upstream Fields: ${JSON.stringify(task.diffDetails.addedFields)}
- Type Mismatches: ${JSON.stringify(task.diffDetails.typeMismatches)}

Sample Observed Payload:
${JSON.stringify(task.samplePayload, null, 2)}

Strict Rules:
1. Output ONLY a valid ES6 arrow function, e.g.: (data) => ({ ...data, firstName: data.first_name })
2. Do NOT include markdown formatting, backticks, or explanatory text.
3. No imports, no network requests, no eval, no mutations. Pure transformation.
4. Use optional chaining and nullish coalescing (??).
`;
}

function buildRenameAdapter(diff: PatchGenerationTask['diffDetails']): string {
  const mappings: string[] = [];
  for (const expectedField of diff.missingFields) {
    const observedField = diff.addedFields.find(
      (field) =>
        field.replace(/_/g, '').toLowerCase() === expectedField.toLowerCase(),
    );
    if (observedField) mappings.push(`${expectedField}: data.${observedField}`);
  }
  return `(data) => ({ ...data, ${mappings.join(', ')} })`;
}
