import { Inject, Injectable, Logger } from '@nestjs/common';
import { generateText } from '@orchestrator/gemini-client';
import { OrgSettingsService } from '../orgs/org-settings.service.js';
import { CircuitBreakerService } from '../common/circuit-breaker.service.js';
import { TimeoutError } from '../common/resilience.decorators.js';
import { buildRenameAdapter } from './fallback-adapter.js';
import type {
  GeneratedAdapter,
  PatchGenerationTask,
} from './patch-generation.js';

const FALLBACK_TRACE =
  'Synthesized via Deterministic AST Field-Mapping Fallback Engine';

// Mirrors what validateAdapterAst and the sandbox accept, so valid output is the norm.
const SYSTEM_INSTRUCTION = `You are an expert JavaScript systems engineer repairing API contract drift.
Return ONLY one synchronous JavaScript arrow function (data) => ... that converts the observed payload back to the expected schema.
Rules:
- No markdown, backticks, comments or explanation.
- Pure transformation: no imports, network, timers, eval, Function, this, globalThis, process, constructor, prototype or __proto__.
- Do not mutate the input; build and return a new object.
- Use optional chaining and nullish coalescing (??) for fields that may be absent.`;

@Injectable()
export class InferenceService {
  private readonly logger = new Logger(InferenceService.name);

  constructor(
    @Inject(OrgSettingsService) private readonly settings: OrgSettingsService,
    @Inject(CircuitBreakerService)
    private readonly breaker: CircuitBreakerService,
  ) {}

  async generate(task: PatchGenerationTask): Promise<GeneratedAdapter> {
    // Each organization may bring its own Gemini key and model.
    const { apiKey, model } = (await this.settings.effective(task.orgId))
      .gemini;
    if (!apiKey) return this.fallback(task, 'GEMINI_API_KEY is not set');

    // Use circuit breaker to prevent cascading failures if Gemini is down
    const circuitBreaker = this.breaker.get('gemini-api', {
      failureThreshold: 3,
      resetTimeoutMs: 60_000,
    });

    try {
      // Attempt with circuit breaker + timeout protection
      const response = await circuitBreaker.execute(
        () =>
          this.callGeminiWithTimeout(
            { apiKey, model, systemInstruction: SYSTEM_INSTRUCTION },
            buildAdapterPrompt(task),
          ),
      );

      if (!response) {
        return this.fallback(task, 'Gemini circuit breaker is open');
      }

      return {
        adapterCode: response.replace(/```(javascript|js)?/g, '').trim(),
        reasoningTrace: `Generated by Gemini (${model})`,
      };
    } catch (error: unknown) {
      const reason =
        error instanceof TimeoutError
          ? 'Gemini timeout'
          : `Gemini unavailable: ${String(error)}`;
      return this.fallback(task, reason);
    }
  }

  private callGeminiWithTimeout(
    config: {
      apiKey: string;
      model: string;
      systemInstruction: string;
    },
    prompt: string,
  ): Promise<string> {
    // 10s timeout for Gemini; allows circuit breaker to decide if it's failing
    return Promise.race([
      generateText({
        apiKey: config.apiKey,
        model: config.model,
        systemInstruction: config.systemInstruction,
        prompt,
        timeoutMs: 10_000, // Explicit timeout passed to gemini-client
      }),
      new Promise<string>((_, reject) =>
        setTimeout(() => reject(new TimeoutError('Gemini timeout')), 10_000),
      ),
    ]);
  }

  private fallback(
    task: PatchGenerationTask,
    reason: string,
  ): GeneratedAdapter {
    this.logger.warn(`${reason}. Using field-rename fallback.`);
    return {
      adapterCode: buildRenameAdapter(task.diffDetails),
      reasoningTrace: FALLBACK_TRACE,
    };
  }
}

function buildAdapterPrompt(task: PatchGenerationTask): string {
  return `Service: ${task.serviceName}
Endpoint: ${task.httpMethod} ${task.endpointPath}
Expected schema (path:type tokens): ${JSON.stringify(task.expectedSchema)}
Missing expected fields: ${JSON.stringify(task.diffDetails.missingFields)}
Added upstream fields: ${JSON.stringify(task.diffDetails.addedFields)}
Type mismatches: ${JSON.stringify(task.diffDetails.typeMismatches)}

Sample observed payload:
${JSON.stringify(task.samplePayload, null, 2)}`;
}
