import type { DetailedDiff } from '@orchestrator/core';
import type { ContractRef } from '../common/contract-ref.js';

export interface PatchGenerationTask extends ContractRef {
  driftEventId: string;
  contractId: string;
  expectedSchema: string[];
  diffDetails: DetailedDiff;
  samplePayload: unknown;
}

export interface GeneratedAdapter {
  adapterCode: string;
  reasoningTrace: string;
}

export interface SavedPatch {
  patchId: string;
  adapterCode: string;
}

export type PatchGenerator = 'gemini' | 'fallback' | 'unknown';

/** Recovers which engine wrote an adapter from its audit reasoning trace. */
export function generatorOf(
  reasoningTrace: string | null | undefined,
): PatchGenerator {
  if (!reasoningTrace) return 'unknown';
  if (reasoningTrace.startsWith('Generated by Gemini')) return 'gemini';
  if (reasoningTrace.includes('Fallback')) return 'fallback';
  return 'unknown';
}
