import type { GatewayEvent } from '@orchestrator/shared-types';
import {
  ArrowUpCircle,
  CircleSlash,
  Radar,
  Rocket,
  Send,
  Sparkles,
  Undo2,
  type LucideIcon,
} from 'lucide-react';
import { Link } from 'react-router';
import { useLiveEvents } from '@/lib/events';
import { contractLabel, percent, relativeTime } from '@/lib/format';
import { cn } from '@/lib/utils';

interface Described {
  icon: LucideIcon;
  tone: string;
  title: string;
  detail: string;
  href?: string;
}

export function describeEvent(event: GatewayEvent): Described {
  const where = `${event.contract.serviceName} · ${contractLabel(event.contract)}`;
  switch (event.type) {
    case 'drift.detected':
      return {
        icon: Radar,
        tone: event.isBreaking ? 'text-destructive' : 'text-warning',
        title: `${event.isBreaking ? 'Breaking' : 'Non-breaking'} drift detected (${event.driftType.toLowerCase().replace('_', ' ')})`,
        detail: `${where} · coefficient ${event.coefficient.toFixed(2)}`,
        href: `/drift/${event.driftEventId}`,
      };
    case 'patch.generated':
      return {
        icon: Sparkles,
        tone: 'text-primary',
        title: `Patch generated by ${event.generator === 'gemini' ? 'Gemini' : 'fallback engine'}`,
        detail: `${where} · confidence ${percent(event.confidenceScore)}`,
        href: `/patches/${event.patchId}`,
      };
    case 'patch.rejected':
      return {
        icon: CircleSlash,
        tone: 'text-destructive',
        title: 'Generated patch rejected by verification',
        detail: `${where} · ${event.reason}`,
        href: `/patches/${event.patchId}`,
      };
    case 'patch.deployed':
      return {
        icon: Rocket,
        tone: 'text-primary',
        title: `Canary deployed to ${event.canaryPercent}% of traffic`,
        detail: where,
        href: `/patches/${event.patchId}`,
      };
    case 'patch.promoted':
      return {
        icon: ArrowUpCircle,
        tone: 'text-success',
        title: 'Patch promoted to 100% of traffic',
        detail: where,
        href: `/patches/${event.patchId}`,
      };
    case 'patch.rolledBack':
      return {
        icon: Undo2,
        tone: 'text-destructive',
        title: 'Patch rolled back',
        detail: where,
        href: `/patches/${event.patchId}`,
      };
    case 'request.proxied':
      return {
        icon: Send,
        tone: event.isPatched ? 'text-success' : 'text-muted-foreground',
        title: `${event.status} ${event.isPatched ? 'healed response' : 'response'}`,
        detail: where,
      };
  }
}

export function ActivityFeed({
  limit = 12,
  includeRequests = false,
  className,
}: {
  limit?: number;
  includeRequests?: boolean;
  className?: string;
}) {
  const { events, status } = useLiveEvents();
  const visible = events
    .filter((event) => includeRequests || event.type !== 'request.proxied')
    .slice(0, limit);

  if (!visible.length)
    return (
      <p className={cn('py-8 text-center text-sm text-muted-foreground', className)}>
        {status === 'live'
          ? 'Listening… pipeline events will appear here as they happen.'
          : 'Connecting to the live event stream…'}
      </p>
    );

  return (
    <ol className={cn('space-y-1', className)}>
      {visible.map((event, index) => {
        const { icon: Icon, tone, title, detail, href } = describeEvent(event);
        const body = (
          <div className="flex gap-3 rounded-md px-2 py-2 transition-colors hover:bg-muted/60">
            <Icon className={cn('mt-0.5 size-4 shrink-0', tone)} />
            <div className="min-w-0 flex-1">
              <p className="text-sm font-medium">{title}</p>
              <p className="truncate text-xs text-muted-foreground">{detail}</p>
            </div>
            <time className="shrink-0 text-xs text-muted-foreground" dateTime={event.at}>
              {relativeTime(event.at)}
            </time>
          </div>
        );
        return (
          <li key={`${event.at}-${index}`} className="animate-in fade-in slide-in-from-top-1">
            {href ? <Link to={href}>{body}</Link> : body}
          </li>
        );
      })}
    </ol>
  );
}
